import type { GeneratedReport, ReportAnalytics } from "@/types/reports";

function downloadBlob(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function escapeCsv(value: string | number): string {
  return `"${String(value).replace(/"/g, '""')}"`;
}

export function exportReportExcel(
  report: GeneratedReport,
  analytics: ReportAnalytics
) {
  const rows: string[][] = [
    ["Report Name", report.reportName],
    ["Type", report.reportType],
    ["Period", report.periodLabel],
    ["Generated By", report.generatedBy],
    ["Generated At", `${report.dateLabel} ${report.timeLabel}`],
    [],
    ["Metric", "Value"],
    ["Total Collections", String(analytics.kpis.totalCollections)],
    ["Total Complaints", String(analytics.kpis.totalComplaints)],
    ["Active Drivers", String(analytics.kpis.activeDrivers)],
    ["Collection Rate", `${analytics.kpis.collectionRate}%`],
    ["Total Waste Collected (kg)", String(analytics.kpis.totalWasteKg)],
    [],
    ["Top Barangays", "Collections"],
    ...analytics.topBarangays.map((b) => [
      b.barangay,
      String(b.collections),
    ]),
    [],
    ["Status", "Count", "Percentage"],
    ...analytics.statusBreakdown.map((s) => [
      s.label,
      String(s.count),
      `${s.percentage}%`,
    ]),
  ];

  const csv = rows.map((row) => row.map(escapeCsv).join(",")).join("\n");
  const safeName = report.reportName.replace(/\s+/g, "_").toLowerCase();
  downloadBlob(`${safeName}.csv`, csv, "text/csv;charset=utf-8;");
}

export function exportReportPdf(
  report: GeneratedReport,
  analytics: ReportAnalytics
) {
  const html = `<!DOCTYPE html>
<html><head><title>${report.reportName}</title>
<style>
  body { font-family: Arial, sans-serif; padding: 32px; color: #111; }
  h1 { font-size: 20px; margin-bottom: 4px; }
  p.meta { color: #666; font-size: 12px; margin: 0 0 20px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
  th, td { border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 12px; }
  th { background: #f4f6f5; }
</style></head><body>
  <h1>${report.reportName}</h1>
  <p class="meta">${report.periodLabel} · Generated by ${report.generatedBy} · ${report.dateLabel} ${report.timeLabel}</p>
  <table>
    <tr><th>Metric</th><th>Value</th></tr>
    <tr><td>Total Collections</td><td>${analytics.kpis.totalCollections}</td></tr>
    <tr><td>Total Complaints</td><td>${analytics.kpis.totalComplaints}</td></tr>
    <tr><td>Active Drivers</td><td>${analytics.kpis.activeDrivers}</td></tr>
    <tr><td>Collection Rate</td><td>${analytics.kpis.collectionRate}%</td></tr>
    <tr><td>Total Waste Collected</td><td>${analytics.kpis.totalWasteKg.toLocaleString()} kg</td></tr>
  </table>
  <h2>Top Barangays</h2>
  <table>
    <tr><th>Barangay</th><th>Collections</th></tr>
    ${analytics.topBarangays.map((b) => `<tr><td>${b.barangay}</td><td>${b.collections}</td></tr>`).join("")}
  </table>
  <h2>Collection by Status</h2>
  <table>
    <tr><th>Status</th><th>Count</th><th>Percentage</th></tr>
    ${analytics.statusBreakdown.map((s) => `<tr><td>${s.label}</td><td>${s.count}</td><td>${s.percentage}%</td></tr>`).join("")}
  </table>
</body></html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
  win.print();
}
