"use client";

import { ChevronLeft, ChevronRight } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { ReportAnalytics, ReportFilters } from "@/types/reports";
import { exportReportExcel, exportReportPdf } from "@/lib/reports/export";
import type { GeneratedReport } from "@/types/reports";
import { REPORT_TYPE_META } from "@/types/reports";

type Props = {
  reports: GeneratedReport[];
  analytics: ReportAnalytics;
  reportTypeFilter: ReportFilters["reportType"];
};

const PAGE_SIZE = 6;

export default function RecentReportsTable({
  reports,
  analytics,
  reportTypeFilter,
}: Props) {
  const [page, setPage] = useState(1);

  const filtered = useMemo(() => {
    const list =
      reportTypeFilter === "all"
        ? reports
        : reports.filter((r) => r.reportType === reportTypeFilter);
    return [...list].sort(
      (a, b) =>
        new Date(b.generatedAt).getTime() - new Date(a.generatedAt).getTime()
    );
  }, [reports, reportTypeFilter]);

  useEffect(() => {
    setPage(1);
  }, [reportTypeFilter]);

  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const currentPage = Math.min(page, totalPages);
  const pageItems = filtered.slice(
    (currentPage - 1) * PAGE_SIZE,
    currentPage * PAGE_SIZE
  );
  const rangeStart =
    filtered.length === 0 ? 0 : (currentPage - 1) * PAGE_SIZE + 1;
  const rangeEnd = Math.min(currentPage * PAGE_SIZE, filtered.length);

  return (
    <div className="dashboard-card flex min-h-0 flex-col overflow-hidden">
      <div className="border-b border-gray-100 px-4 py-3">
        <h3 className="text-sm font-bold text-gray-900">Recent Reports</h3>
      </div>

      <div className="overflow-auto">
        <table className="w-full min-w-[720px] text-left text-sm">
          <thead className="border-b border-gray-200 bg-gray-50/95">
            <tr>
              {[
                "Report Name",
                "Type",
                "Period",
                "Generated By",
                "Date Generated",
                "Action",
              ].map((col) => (
                <th
                  key={col}
                  className="px-4 py-3 text-xs font-bold uppercase tracking-wide text-gray-700"
                >
                  {col}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {filtered.length === 0 ? (
              <tr>
                <td
                  colSpan={6}
                  className="px-4 py-8 text-center text-sm text-gray-500"
                >
                  No reports generated yet. Click &quot;Generate Reports&quot; to
                  create one.
                </td>
              </tr>
            ) : (
              pageItems.map((row) => {
                const meta =
                  REPORT_TYPE_META[
                    row.reportType as Exclude<typeof row.reportType, "all">
                  ];
                const Icon = meta.icon;
                return (
                  <tr
                    key={row.id}
                    className="border-b border-gray-100 last:border-0 hover:bg-gray-50/60"
                  >
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-2">
                        <span
                          className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${meta.iconBg}`}
                        >
                          <Icon className={`h-4 w-4 ${meta.iconColor}`} />
                        </span>
                        <span className="font-medium text-gray-900">
                          {row.reportName}
                        </span>
                      </div>
                    </td>
                    <td className="px-4 py-3 capitalize text-gray-700">
                      {row.reportType.replace("_", " ")}
                    </td>
                    <td className="px-4 py-3 text-gray-700">{row.periodLabel}</td>
                    <td className="px-4 py-3 text-gray-700">{row.generatedBy}</td>
                    <td className="px-4 py-3 text-gray-700">
                      <div>{row.dateLabel}</div>
                      <div className="text-xs text-gray-500">{row.timeLabel}</div>
                    </td>
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-2">
                        <button
                          type="button"
                          onClick={() => exportReportPdf(row, analytics)}
                          className="rounded-md border border-eco-primary px-2.5 py-1 text-xs font-semibold text-eco-primary hover:bg-eco-light"
                        >
                          PDF
                        </button>
                        <button
                          type="button"
                          onClick={() => exportReportExcel(row, analytics)}
                          className="rounded-md border border-eco-primary px-2.5 py-1 text-xs font-semibold text-eco-primary hover:bg-eco-light"
                        >
                          Excel
                        </button>
                      </div>
                    </td>
                  </tr>
                );
              })
            )}
          </tbody>
        </table>
      </div>

      <div className="flex items-center justify-between border-t border-gray-100 px-4 py-2">
        <p className="text-xs text-gray-500">
          Showing {rangeStart} to {rangeEnd} of {filtered.length} entries
        </p>
        <div className="flex items-center gap-1">
          <button
            type="button"
            onClick={() => setPage((p) => Math.max(1, p - 1))}
            disabled={currentPage <= 1}
            className="rounded-md border border-gray-200 p-1.5 text-gray-600 disabled:opacity-40"
            aria-label="Previous page"
          >
            <ChevronLeft className="h-4 w-4" />
          </button>
          <span className="flex h-8 w-8 items-center justify-center rounded-md bg-eco-primary text-sm font-semibold text-white">
            {currentPage}
          </span>
          <button
            type="button"
            onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
            disabled={currentPage >= totalPages}
            className="rounded-md border border-gray-200 p-1.5 text-gray-600 disabled:opacity-40"
            aria-label="Next page"
          >
            <ChevronRight className="h-4 w-4" />
          </button>
        </div>
      </div>
    </div>
  );
}
